# Generated by Django 4.2.16

import django.db.models.deletion
import uuid

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LogicQuestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=120)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("number", "数字推理"),
                            ("figure", "图形推理"),
                            ("logic", "逻辑判断"),
                            ("analogy", "类比推理"),
                            ("deduction", "演绎推理"),
                        ],
                        max_length=32,
                    ),
                ),
                ("difficulty", models.CharField(max_length=16)),
                ("stem", models.TextField()),
                ("answer", models.CharField(max_length=32)),
                ("explanation", models.TextField()),
                ("knowledge", models.CharField(max_length=120)),
                ("image", models.ImageField(blank=True, upload_to="questions/")),
            ],
        ),
        migrations.CreateModel(
            name="WrongBookEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("mistakes", models.PositiveIntegerField(default=1)),
                ("favorited", models.BooleanField(default=False)),
                ("last_practiced_at", models.DateField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bank.logicquestion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "question")},
            },
        ),
        migrations.CreateModel(
            name="ExamDraft",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("paper_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("difficulty", models.CharField(max_length=16)),
                ("amount", models.PositiveIntegerField()),
                ("questions", models.JSONField(default=list)),
                ("answers", models.JSONField(default=dict)),
                ("unsure", models.JSONField(default=list)),
                ("current_index", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "进行中"), ("submitted", "已交卷")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["user", "status"], name="bank_examdr_user_id_idx")],
            },
        ),
        migrations.CreateModel(
            name="ExamSubmission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("paper_id", models.UUIDField(unique=True)),
                ("answers", models.JSONField(default=dict)),
                ("unsure", models.JSONField(default=list)),
                ("score", models.PositiveIntegerField()),
                ("total", models.PositiveIntegerField()),
                ("correct", models.PositiveIntegerField()),
                ("report", models.JSONField(default=dict)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
